sonar.projectKey=crgolden_Infrastructure
sonar.organization=crgolden

sonar.sources=Infrastructure
sonar.tests=Infrastructure.Tests
sonar.exclusions=**/bin/**,**/obj/**

sonar.cs.vscoveragexml.reportsPaths=coverage.xml
